name: "TFTP server"
description: "Simple tftp server"
version: "1.0.0"
slug: "tftp"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

# Changing "share" to "share:rw" gives the container read/write access
map:
  - "share:rw"

ports:
  69/udp: 69
